# Generated by Django 6.0.4 on 2026-05-02 16:06

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('date', models.DateTimeField()),
                ('is_published', models.BooleanField(default=True)),
                ('full_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Полное содержание')),
            ],
        ),
    ]
