services:
  # Сервис для PostgreSQL (база данных)
  db:
    image: postgres:17
    container_name: astrotsu_db
    env_file: .env.prod
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - internal
    restart: always
      
  # Сервис для Django (backend)    
  backend:
    build:
      context: ./backend  # Смотрит Dockerfile в текущей директории (.)
      dockerfile: Dockerfile # Имя Dockerfile для бэкенда
    platform: linux/amd64
    container_name: astrotsu_backend
    env_file: .env.prod
    ports:
      - "8000:8000"
    volumes:
      - /html/media:/app/media
      - /html/staticfiles:/app/staticfiles 
    depends_on:
      - db # Дожидается старта сервиса базы данных
#    command: "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 --timeout 120 astro_tsu_admin.wsgi:application" # эти команды есть docker-entrypoint.sh
    networks:
      - internal
    restart: always

networks:
  internal:
    driver: bridge