# Generated by Django 6.0.4 on 2026-05-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='persona',
            field=models.URLField(blank=True, null=True),
        ),
    ]
