# Generated by Django 6.0.4 on 2026-05-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teachers_persona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'ordering': ['order'], 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='teachers',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
