server {
    listen 80;
    listen 443 ssl;
    server_name astro.tsu.ru www.astro.tsu.ru;

    root /usr/share/nginx/html;
    index index.html index.htm;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /static/ {
        alias /staticfiles/;
        expires 30d;
    }

    location /media/ {
        alias /media/;
    }
}
