# Generated by Django 6.0.4 on 2026-05-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
                ('spisok', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
