# Generated by Django 6.0.4 on 2026-05-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['order'], 'verbose_name_plural': 'Year'},
        ),
        migrations.AddField(
            model_name='alumni',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
