# Generated by Django 6.0.5 on 2026-06-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0002_alter_alumni_options_alumni_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['order'], 'verbose_name_plural': 'Год выпуска'},
        ),
    ]
